
import base64, os
data = base64.b64decode("I2luY2x1ZGUgPHN0ZGxpYi5oPgojaW5jbHVkZSA8c3RyaW5nLmg+CiNpbmNsdWRlIDxzdGRpby5oPgojaW5jbHVkZSAib21lZ2FfcmVndWxhci5oIgoKYm9vbCBvbWVnYV93b3JkX2NyZWF0ZShvbWVnYV93b3JkICpvdywKICAgICAgICAgICAgICAgICAgICAgICBjb25zdCB1aW50OF90ICpwcmVmaXgsIHNpemVfdCBwbGVuLAogICAgICAgICAgICAgICAgICAgICAgIGNvbnN0IHVpbnQ4X3QgKnBlcmlvZCwgc2l6ZV90IHJsZW4pCnsKICAgIGlmICghb3cpIHJldHVybiBmYWxzZTsKICAgIGlmIChwbGVuID4gT1JfTUFYX1BSRUZJWCB8fCBybGVuID4gT1JfTUFYX1BSRUZJWCkgcmV0dXJuIGZhbHNlOwogICAgbWVtc2V0KG93LCAwLCBzaXplb2YoKm93KSk7CiAgICBpZiAocHJlZml4ICYmIHBsZW4gPiAwKSB7CiAgICAgICAgbWVtY3B5KG93LT5wcmVmaXgsIHByZWZpeCwgcGxlbik7CiAgICAgICAgb3ctPnByZWZpeF9sZW4gPSBwbGVuOwogICAgfQogICAgaWYgKHBlcmlvZCAmJiBybGVuID4gMCkgewogICAgICAgIG1lbWNweShvdy0+cGVyaW9kLCBwZXJpb2QsIHJsZW4pOwogICAgICAgIG93LT5wZXJpb2RfbGVuID0gcmxlbjsKICAgIH0KICAgIHJldHVybiB0cnVlOwp9Cg==")
path = r"F:
ano-everything\mini-theory-of-computation9. mini-reactive-verification-synthesis\mini-omega-regular-properties\src\_test_b64.c"
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "wb") as f:
    f.write(data)
print(f"Decoded {len(data)} bytes")
